INSERT INTO pokemon (Nome, Pokedex, Nomedex, Ataque1, Ataque2, Ataque3, Ataque4, Tipo1, Tipo2, Nature, Pokebola, Item_pokemon, Combates, Vitorias, Derrotas, Empate, ID_Treinador)
VALUES
('Spark', 25, 'Pikachu', 'Thunderbolt', 'Quick Attack', 'Iron Tail', 'Electro Ball', 'Electric', NULL, 'Jolly', 'Pokeball', 'None', 50, 30, 15, 5, 'T001'),
('Fluffy', 36, 'Clefairy', 'Moonblast', 'Metronome', 'Sing', 'Body Slam', 'Fairy', NULL, 'Calm', 'Great Ball', 'None', 40, 25, 10, 5, 'T001'),
('Tornado', 17, 'Pidgeotto', 'Gust', 'Quick Attack', 'Wing Attack', 'Feather Dance', 'Flying', 'Normal', 'Brave', 'Pokeball', 'None', 35, 20, 10, 5, 'T001'),
('Rocky', 95, 'Onix', 'Rock Throw', 'Bind', 'Earthquake', 'Slam', 'Rock', 'Ground', 'Adamant', 'Ultra Ball', 'None', 45, 30, 10, 5, 'T001'),
('Blitz', 59, 'Arcanine', 'Flamethrower', 'Crunch', 'Extreme Speed', 'Fire Fang', 'Fire', NULL, 'Bold', 'Ultra Ball', 'None', 60, 40, 15, 5, 'T002'),
('Shadow', 94, 'Gengar', 'Shadow Ball', 'Sludge Bomb', 'Hypnosis', 'Dream Eater', 'Ghost', 'Poison', 'Timid', 'Dusk Ball', 'None', 55, 35, 15, 5, 'T002'),
('Leafy', 3, 'Venusaur', 'Solar Beam', 'Sludge Bomb', 'Earthquake', 'Synthesis', 'Grass', 'Poison', 'Modest', 'Great Ball', 'None', 50, 30, 15, 5, 'T002'),
('Storm', 130, 'Gyarados', 'Waterfall', 'Dragon Dance', 'Ice Fang', 'Hyper Beam', 'Water', 'Flying', 'Brave', 'Pokeball', 'None', 65, 40, 20, 5, 'T002'),
('Magma', 126, 'Magmar', 'Flamethrower', 'Psychic', 'Thunder Punch', 'Fire Blast', 'Fire', NULL, 'Hasty', 'Great Ball', 'None', 40, 25, 10, 5, 'T002'),
('Flash', 135, 'Jolteon', 'Thunderbolt', 'Pin Missile', 'Shadow Ball', 'Quick Attack', 'Electric', NULL, 'Hasty', 'Ultra Ball', 'None', 55, 35, 15, 5, 'T003'),
('Aqua', 134, 'Vaporeon', 'Surf', 'Ice Beam', 'Shadow Ball', 'Hydro Pump', 'Water', NULL, 'Modest', 'Great Ball', 'None', 50, 30, 15, 5, 'T003'),
('Echo', 196, 'Espeon', 'Psychic', 'Dazzling Gleam', 'Shadow Ball', 'Calm Mind', 'Psychic', NULL, 'Timid', 'Pokeball', 'None', 45, 30, 10, 5, 'T003'),
('Thunder', 145, 'Zapdos', 'Thunderbolt', 'Drill Peck', 'Roost', 'Heat Wave', 'Electric', 'Flying', 'Modest', 'Ultra Ball', 'None', 70, 45, 20, 5, 'T004'),
('Blossom', 182, 'Bellossom', 'Solar Beam', 'Moonblast', 'Stun Spore', 'Giga Drain', 'Grass', NULL, 'Calm', 'Pokeball', 'None', 40, 25, 10, 5, 'T004'),
('Inferno', 6, 'Charizard', 'Flamethrower', 'Dragon Claw', 'Fly', 'Fire Blast', 'Fire', 'Flying', 'Adamant', 'Great Ball', 'None', 55, 35, 15, 5, 'T004'),
('Gemini', 18, 'Pidgeot', 'Hurricane', 'Brave Bird', 'Roost', 'Quick Attack', 'Flying', 'Normal', 'Brave', 'Pokeball', 'None', 35, 20, 10, 5, 'T004'),
('Crusher', 112, 'Rhydon', 'Rock Wrecker', 'Earthquake', 'Hammer Arm', 'Megahorn', 'Ground', 'Rock', 'Adamant', 'Ultra Ball', 'None', 50, 35, 10, 5, 'T005'),
('Blaze', 5, 'Charmeleon', 'Flamethrower', 'Dragon Breath', 'Slash', 'Fire Fang', 'Fire', NULL, 'Brave', 'Pokeball', 'None', 40, 25, 10, 5, 'T005'),
('Frost', 131, 'Lapras', 'Ice Beam', 'Surf', 'Dragon Dance', 'Perish Song', 'Ice', 'Water', 'Modest', 'Great Ball', 'None', 45, 30, 10, 5, 'T005'),
('Luna', 39, 'Jigglypuff', 'Dazzling Gleam', 'Hyper Voice', 'Sing', 'Body Slam', 'Fairy', 'Normal', 'Calm', 'Pokeball', 'None', 30, 15, 10, 5, 'T005'),
('Beast', 143, 'Snorlax', 'Body Slam', 'Rest', 'Crunch', 'Earthquake', 'Normal', NULL, 'Relaxed', 'Ultra Ball', 'None', 60, 40, 15, 5, 'T005'),
('Tempest', 149, 'Dragonite', 'Outrage', 'Dragon Dance', 'Hurricane', 'Thunder Punch', 'Dragon', 'Flying', 'Jolly', 'Ultra Ball', 'None', 65, 40, 20, 5, 'T006'),
('Pyro', 136, 'Flareon', 'Flamethrower', 'Quick Attack', 'Superpower', 'Fire Fang', 'Fire', NULL, 'Adamant', 'Pokeball', 'None', 50, 30, 15, 5, 'T006'),
('Swift', 18, 'Pidgeot', 'Hurricane', 'Quick Attack', 'Roost', 'Air Slash', 'Flying', 'Normal', 'Brave', 'Great Ball', 'None', 40, 25, 10, 5, 'T006'),
('Boulder', 95, 'Onix', 'Rock Throw', 'Bind', 'Earthquake', 'Slam', 'Rock', 'Ground', 'Adamant', 'Ultra Ball', 'None', 50, 30, 15, 5, 'T007'),
('Splash', 130, 'Gyarados', 'Waterfall', 'Dragon Dance', 'Ice Fang', 'Hyper Beam', 'Water', 'Flying', 'Brave', 'Pokeball', 'None', 65, 40, 20, 5, 'T007'),
('Cinder', 136, 'Flareon', 'Flamethrower', 'Quick Attack', 'Superpower', 'Fire Fang', 'Fire', NULL, 'Adamant', 'Pokeball', 'None', 40, 25, 10, 5, 'T007'),
('Venom', 49, 'Venomoth', 'Bug Buzz', 'Sludge Bomb', 'Psychic', 'Quiver Dance', 'Bug', 'Poison', 'Timid', 'Great Ball', 'None', 45, 30, 10, 5, 'T007'),
('Windy', 144, 'Articuno', 'Ice Beam', 'Hurricane', 'Roost', 'Freeze-Dry', 'Ice', 'Flying', 'Calm', 'Ultra Ball', 'None', 70, 45, 20, 5, 'T008'),
('Flare', 126, 'Magmar', 'Flamethrower', 'Psychic', 'Thunder Punch', 'Fire Blast', 'Fire', NULL, 'Hasty', 'Great Ball', 'None', 40, 25, 10, 5, 'T008'),
('Spike', 111, 'Rhyhorn', 'Earthquake', 'Rock Blast', 'Megahorn', 'Crunch', 'Ground', 'Rock', 'Adamant', 'Pokeball', 'None', 35, 20, 10, 5, 'T008'),
('Glare', 101, 'Electrode', 'Thunderbolt', 'Volt Switch', 'Explosion', 'Light Screen', 'Electric', NULL, 'Timid', 'Ultra Ball', 'None', 45, 30, 10, 5, 'T008'),
('Bolt', 135, 'Jolteon', 'Thunderbolt', 'Shadow Ball', 'Pin Missile', 'Quick Attack', 'Electric', NULL, 'Timid', 'Ultra Ball', 'None', 50, 30, 15, 5, 'T009'),
('Rage', 115, 'Kangaskhan', 'Double-Edge', 'Crunch', 'Earthquake', 'Fake Out', 'Normal', NULL, 'Adamant', 'Great Ball', 'None', 45, 25, 15, 5, 'T009'),
('Frostbite', 131, 'Lapras', 'Ice Beam', 'Surf', 'Dragon Dance', 'Perish Song', 'Ice', 'Water', 'Calm', 'Pokeball', 'None', 55, 35, 15, 5, 'T009'),
('Vortex', 130, 'Gyarados', 'Waterfall', 'Dragon Dance', 'Hyper Beam', 'Ice Fang', 'Water', 'Flying', 'Brave', 'Ultra Ball', 'None', 60, 40, 15, 5, 'T009'),
('Ivy', 3, 'Venusaur', 'Solar Beam', 'Sludge Bomb', 'Earthquake', 'Synthesis', 'Grass', 'Poison', 'Modest', 'Great Ball', 'None', 50, 30, 15, 5, 'T009'),
('Steel', 208, 'Steelix', 'Iron Tail', 'Earthquake', 'Rock Slide', 'Crunch', 'Steel', 'Ground', 'Bold', 'Pokeball', 'None', 45, 30, 10, 5, 'T009'),
('Whiskers', 52, 'Persian', 'Fake Out', 'Shadow Claw', 'Power Gem', 'U-turn', 'Normal', NULL, 'Jolly', 'Ultra Ball', 'None', 40, 25, 10, 5, 'T010'),
('Inferno', 59, 'Arcanine', 'Flamethrower', 'Crunch', 'Extreme Speed', 'Fire Fang', 'Fire', NULL, 'Brave', 'Pokeball', 'None', 50, 30, 15, 5, 'T010'),
('Rocky', 112, 'Rhydon', 'Earthquake', 'Rock Blast', 'Hammer Arm', 'Megahorn', 'Ground', 'Rock', 'Adamant', 'Great Ball', 'None', 45, 30, 10, 5, 'T010'),
('Zephyr', 18, 'Pidgeot', 'Hurricane', 'Brave Bird', 'Roost', 'Heat Wave', 'Flying', 'Normal', 'Brave', 'Ultra Ball', 'None', 55, 35, 15, 5, 'T011'),
('Hurricane', 149, 'Dragonite', 'Outrage', 'Thunder Punch', 'Fire Punch', 'Hurricane', 'Dragon', 'Flying', 'Adamant', 'Great Ball', 'None', 60, 40, 15, 5, 'T011'),
('Claw', 6, 'Charizard', 'Flamethrower', 'Dragon Claw', 'Roost', 'Fire Blast', 'Fire', 'Flying', 'Modest', 'Pokeball', 'None', 50, 30, 15, 5, 'T011'),
('Bramble', 45, 'Vileplume', 'Solar Beam', 'Sludge Bomb', 'Moonblast', 'Stun Spore', 'Grass', 'Poison', 'Calm', 'Ultra Ball', 'None', 45, 30, 10, 5, 'T011'),
('Fluffy', 39, 'Jigglypuff', 'Sing', 'Hyper Voice', 'Dazzling Gleam', 'Body Slam', 'Fairy', 'Normal', 'Timid', 'Great Ball', 'None', 35, 20, 10, 5, 'T012'),
('Snappy', 159, 'Croconaw', 'Water Gun', 'Crunch', 'Ice Fang', 'Aqua Tail', 'Water', NULL, 'Adamant', 'Pokeball', 'None', 45, 30, 15, 5, 'T012'),
('Fang', 24, 'Arbok', 'Poison Fang', 'Crunch', 'Glare', 'Gunk Shot', 'Poison', NULL, 'Brave', 'Ultra Ball', 'None', 40, 25, 10, 5, 'T012'),
('Blizzard', 471, 'Glaceon', 'Ice Beam', 'Shadow Ball', 'Water Pulse', 'Blizzard', 'Ice', NULL, 'Calm', 'Great Ball', 'None', 50, 30, 15, 5, 'T012'),
('Ember', 4, 'Charmander', 'Flamethrower', 'Scratch', 'Dragon Claw', 'Fire Fang', 'Fire', NULL, 'Jolly', 'Pokeball', 'None', 35, 20, 10, 5, 'T013'),
('Stormy', 55, 'Golduck', 'Surf', 'Ice Beam', 'Zen Headbutt', 'Aqua Tail', 'Water', NULL, 'Calm', 'Great Ball', 'None', 40, 25, 10, 5, 'T013'),
('Hydra', 130, 'Gyarados', 'Waterfall', 'Dragon Dance', 'Ice Fang', 'Crunch', 'Water', 'Flying', 'Brave', 'Ultra Ball', 'None', 50, 30, 15, 5, 'T013'),
('Sunny', 38, 'Ninetales', 'Flamethrower', 'Solar Beam', 'Extrasensory', 'Will-O-Wisp', 'Fire', NULL, 'Modest', 'Great Ball', 'None', 45, 30, 10, 5, 'T014'),
('Slash', 28, 'Sandslash', 'Earthquake', 'Rock Slide', 'Slash', 'Iron Head', 'Ground', NULL, 'Adamant', 'Pokeball', 'None', 40, 25, 10, 5, 'T014'),
('Wisp', 302, 'Sableye', 'Shadow Sneak', 'Fake Out', 'Will-O-Wisp', 'Knock Off', 'Ghost', 'Dark', 'Brave', 'Ultra Ball', 'None', 35, 20, 10, 5, 'T014'),
('Flame', 5, 'Charmeleon', 'Flamethrower', 'Dragon Claw', 'Fire Fang', 'Slash', 'Fire', NULL, 'Hasty', 'Pokeball', 'None', 45, 30, 15, 5, 'T014'),
('Drake', 149, 'Dragonite', 'Outrage', 'Thunder Punch', 'Fire Punch', 'Dragon Claw', 'Dragon', 'Flying', 'Brave', 'Great Ball', 'None', 65, 40, 20, 5, 'T015'),
('Talon', 6, 'Charizard', 'Flamethrower', 'Fly', 'Dragon Claw', 'Fire Blast', 'Fire', 'Flying', 'Adamant', 'Pokeball', 'None', 50, 30, 15, 5, 'T015'),
('Ghost', 93, 'Haunter', 'Shadow Ball', 'Sludge Bomb', 'Hypnosis', 'Dark Pulse', 'Ghost', 'Poison', 'Timid', 'Ultra Ball', 'None', 45, 30, 15, 5, 'T015'),
('Razor', 452, 'Drapion', 'Poison Fang', 'Night Slash', 'Earthquake', 'Crunch', 'Poison', 'Dark', 'Adamant', 'Great Ball', 'None', 50, 30, 15, 5, 'T015'),
('Shimmer', 330, 'Flygon', 'Earthquake', 'Dragon Claw', 'Stone Edge', 'U-turn', 'Ground', 'Dragon', 'Jolly', 'Ultra Ball', 'None', 55, 35, 15, 5, 'T015'),
('Spikey', 111, 'Rhyhorn', 'Earthquake', 'Stone Edge', 'Crunch', 'Megahorn', 'Ground', 'Rock', 'Adamant', 'Ultra Ball', 'None', 50, 35, 10, 5, 'T016'),
('Thunder', 135, 'Jolteon', 'Thunderbolt', 'Shadow Ball', 'Volt Switch', 'Thunder Wave', 'Electric', NULL, 'Timid', 'Great Ball', 'None', 45, 30, 10, 5, 'T016'),
('Lava', 219, 'Magcargo', 'Lava Plume', 'Rock Slide', 'Shell Smash', 'Earth Power', 'Fire', 'Rock', 'Calm', 'Pokeball', 'None', 35, 20, 10, 5, 'T016'),
('Claw', 6, 'Charizard', 'Flamethrower', 'Dragon Claw', 'Fly', 'Roost', 'Fire', 'Flying', 'Brave', 'Ultra Ball', 'None', 50, 30, 15, 5, 'T017'),
('Boulder', 76, 'Golem', 'Earthquake', 'Stone Edge', 'Explosion', 'Stealth Rock', 'Rock', 'Ground', 'Adamant', 'Great Ball', 'None', 45, 25, 15, 5, 'T017'),
('Twister', 149, 'Dragonite', 'Outrage', 'Hurricane', 'Fire Punch', 'Extreme Speed', 'Dragon', 'Flying', 'Jolly', 'Pokeball', 'None', 55, 35, 15, 5, 'T017'),
('Mystic', 131, 'Lapras', 'Ice Beam', 'Surf', 'Thunderbolt', 'Psychic', 'Water', 'Ice', 'Modest', 'Ultra Ball', 'None', 50, 30, 15, 5, 'T018'),
('Blade', 475, 'Gallade', 'Psycho Cut', 'Close Combat', 'Leaf Blade', 'Swords Dance', 'Psychic', 'Fighting', 'Adamant', 'Pokeball', 'None', 45, 30, 10, 5, 'T018'),
('Frost', 471, 'Glaceon', 'Ice Beam', 'Shadow Ball', 'Water Pulse', 'Blizzard', 'Ice', NULL, 'Timid', 'Great Ball', 'None', 40, 25, 10, 5, 'T018'),
('Spark', 135, 'Jolteon', 'Thunderbolt', 'Volt Switch', 'Shadow Ball', 'Thunder Wave', 'Electric', NULL, 'Timid', 'Pokeball', 'None', 45, 30, 15, 5, 'T018'),
('Echo', 130, 'Gyarados', 'Waterfall', 'Crunch', 'Ice Fang', 'Dragon Dance', 'Water', 'Flying', 'Brave', 'Ultra Ball', 'None', 50, 30, 10, 10, 'T019'),
('Tornado', 18, 'Pidgeot', 'Hurricane', 'Heat Wave', 'Roost', 'U-turn', 'Flying', 'Normal', 'Jolly', 'Pokeball', 'None', 40, 25, 10, 5, 'T019'),
('Spark', 125, 'Electabuzz', 'Thunderbolt', 'Volt Switch', 'Low Kick', 'Thunder Punch', 'Electric', NULL, 'Modest', 'Great Ball', 'None', 45, 30, 10, 5, 'T019'),
('Flare', 38, 'Ninetales', 'Flamethrower', 'Solar Beam', 'Will-O-Wisp', 'Extrasensory', 'Fire', NULL, 'Calm', 'Pokeball', 'None', 45, 30, 15, 5, 'T019'),
('Wings', 227, 'Skarmory', 'Brave Bird', 'Roost', 'Spikes', 'Steel Wing', 'Steel', 'Flying', 'Impish', 'Ultra Ball', 'None', 50, 35, 10, 5, 'T020'),
('Rocky', 112, 'Rhydon', 'Earthquake', 'Rock Blast', 'Megahorn', 'Crunch', 'Ground', 'Rock', 'Adamant', 'Great Ball', 'None', 40, 25, 10, 5, 'T020'),
('Thunder', 135, 'Jolteon', 'Thunderbolt', 'Volt Switch', 'Thunder Wave', 'Shadow Ball', 'Electric', NULL, 'Timid', 'Pokeball', 'None', 45, 30, 15, 5, 'T020'),
('Fury', 110, 'Weezing', 'Sludge Bomb', 'Will-O-Wisp', 'Toxic', 'Explosion', 'Poison', NULL, 'Bold', 'Pokeball', 'None', 35, 20, 10, 5, 'T020'),
('Blitz', 310, 'Manectric', 'Thunderbolt', 'Flamethrower', 'Volt Switch', 'Crunch', 'Electric', NULL, 'Timid', 'Ultra Ball', 'None', 50, 35, 10, 5, 'T021'),
('Cinder', 59, 'Arcanine', 'Flamethrower', 'Crunch', 'Extreme Speed', 'Flare Blitz', 'Fire', NULL, 'Adamant', 'Great Ball', 'None', 45, 30, 10, 5, 'T021'),
('Shadow', 302, 'Sableye', 'Shadow Sneak', 'Fake Out', 'Will-O-Wisp', 'Knock Off', 'Ghost', 'Dark', 'Brave', 'Pokeball', 'None', 40, 25, 10, 5, 'T021'),
('Fury', 286, 'Breloom', 'Mach Punch', 'Spore', 'Bullet Seed', 'Rock Tomb', 'Grass', 'Fighting', 'Jolly', 'Great Ball', 'None', 35, 20, 10, 5, 'T021'),
('Scorch', 257, 'Blaziken', 'Flare Blitz', 'High Jump Kick', 'Swords Dance', 'Stone Edge', 'Fire', 'Fighting', 'Adamant', 'Pokeball', 'None', 55, 35, 15, 5, 'T021'),
('Storm', 134, 'Vaporeon', 'Hydro Pump', 'Ice Beam', 'Shadow Ball', 'Aqua Ring', 'Water', NULL, 'Calm', 'Ultra Ball', 'None', 50, 35, 10, 5, 'T022'),
('Echo', 130, 'Gyarados', 'Waterfall', 'Dragon Dance', 'Crunch', 'Ice Fang', 'Water', 'Flying', 'Adamant', 'Pokeball', 'None', 45, 30, 10, 5, 'T022'),
('Flare', 38, 'Ninetales', 'Flamethrower', 'Solar Beam', 'Extrasensory', 'Will-O-Wisp', 'Fire', NULL, 'Modest', 'Great Ball', 'None', 40, 25, 10, 5, 'T022'),
('Ice', 471, 'Glaceon', 'Ice Beam', 'Shadow Ball', 'Water Pulse', 'Blizzard', 'Ice', NULL, 'Modest', 'Great Ball', 'None', 45, 30, 10, 5, 'T023'),
('Steel', 208, 'Steelix', 'Iron Tail', 'Earthquake', 'Rock Slide', 'Crunch', 'Steel', 'Ground', 'Impish', 'Pokeball', 'None', 40, 25, 10, 5, 'T023'),
('Bolt', 135, 'Jolteon', 'Thunderbolt', 'Volt Switch', 'Thunder Wave', 'Shadow Ball', 'Electric', NULL, 'Timid', 'Ultra Ball', 'None', 45, 30, 15, 5, 'T023'),
('Rogue', 197, 'Umbreon', 'Foul Play', 'Toxic', 'Moonlight', 'Snarl', 'Dark', NULL, 'Calm', 'Ultra Ball', 'None', 50, 35, 10, 5, 'T024'),
('Splash', 134, 'Vaporeon', 'Surf', 'Ice Beam', 'Wish', 'Protect', 'Water', NULL, 'Calm', 'Pokeball', 'None', 45, 30, 10, 5, 'T024'),
('Flame', 59, 'Arcanine', 'Flamethrower', 'Crunch', 'Extreme Speed', 'Flare Blitz', 'Fire', NULL, 'Adamant', 'Great Ball', 'None', 40, 25, 10, 5, 'T024'),
('Windy', 18, 'Pidgeot', 'Hurricane', 'Heat Wave', 'Roost', 'Brave Bird', 'Flying', 'Normal', 'Jolly', 'Pokeball', 'None', 40, 25, 10, 5, 'T024'),
('Blizzard', 471, 'Glaceon', 'Ice Beam', 'Shadow Ball', 'Blizzard', 'Water Pulse', 'Ice', NULL, 'Timid', 'Ultra Ball', 'None', 45, 30, 10, 5, 'T025'),
('Crusher', 448, 'Lucario', 'Aura Sphere', 'Close Combat', 'Extreme Speed', 'Dragon Pulse', 'Fighting', 'Steel', 'Adamant', 'Pokeball', 'None', 50, 35, 10, 5, 'T025'),
('Shadow', 302, 'Sableye', 'Fake Out', 'Knock Off', 'Will-O-Wisp', 'Shadow Sneak', 'Dark', 'Ghost', 'Brave', 'Great Ball', 'None', 40, 25, 10, 5, 'T025'),
('Scorch', 257, 'Blaziken', 'Flare Blitz', 'High Jump Kick', 'Swords Dance', 'Stone Edge', 'Fire', 'Fighting', 'Adamant', 'Ultra Ball', 'None', 50, 35, 10, 5, 'T026'),
('Spike', 208, 'Steelix', 'Earthquake', 'Iron Tail', 'Stealth Rock', 'Crunch', 'Steel', 'Ground', 'Impish', 'Great Ball', 'None', 45, 30, 10, 5, 'T026'),
('Breeze', 18, 'Pidgeot', 'Hurricane', 'Roost', 'Brave Bird', 'U-turn', 'Flying', 'Normal', 'Jolly', 'Pokeball', 'None', 40, 25, 10, 5, 'T026'),
('Volt', 310, 'Manectric', 'Thunderbolt', 'Volt Switch', 'Flamethrower', 'Crunch', 'Electric', NULL, 'Timid', 'Pokeball', 'None', 45, 30, 15, 5, 'T026'),
('Talon', 334, 'Altaria', 'Dragon Pulse', 'Moonblast', 'Roost', 'Hurricane', 'Dragon', 'Flying', 'Modest', 'Ultra Ball', 'None', 55, 35, 10, 10, 'T027'),
('Inferno', 5, 'Charmeleon', 'Flamethrower', 'Dragon Rage', 'Fire Spin', 'Will-O-Wisp', 'Fire', NULL, 'Brave', 'Great Ball', 'None', 40, 25, 10, 5, 'T027'),
('Vortex', 227, 'Skarmory', 'Brave Bird', 'Roost', 'Spikes', 'Iron Head', 'Steel', 'Flying', 'Impish', 'Pokeball', 'None', 50, 30, 15, 5, 'T027'),
('Spark', 135, 'Jolteon', 'Thunderbolt', 'Shadow Ball', 'Volt Switch', 'Thunder Wave', 'Electric', NULL, 'Timid', 'Pokeball', 'None', 45, 30, 10, 5, 'T027'),
('Boulder', 112, 'Rhydon', 'Earthquake', 'Rock Blast', 'Crunch', 'Stone Edge', 'Ground', 'Rock', 'Adamant', 'Pokeball', 'None', 50, 30, 10, 10, 'T027'),
('Zephyr', 18, 'Pidgeot', 'Hurricane', 'Heat Wave', 'Roost', 'Brave Bird', 'Flying', 'Normal', 'Jolly', 'Great Ball', 'None', 45, 30, 15, 5, 'T027'),
('Whiskers', 52, 'Persian', 'Slash', 'Thunderbolt', 'Bite', 'Fake Out', 'Normal', NULL, 'Jolly', 'Pokeball', 'None', 40, 25, 10, 5, 'T028'),
('Blaze', 6, 'Charizard', 'Flamethrower', 'Dragon Claw', 'Fly', 'Solar Beam', 'Fire', 'Flying', 'Brave', 'Ultra Ball', 'None', 55, 35, 10, 10, 'T028'),
('Hydra', 130, 'Gyarados', 'Waterfall', 'Crunch', 'Ice Fang', 'Dragon Dance', 'Water', 'Flying', 'Adamant', 'Great Ball', 'None', 45, 30, 10, 5, 'T028'),
('Thunder', 135, 'Jolteon', 'Thunderbolt', 'Volt Switch', 'Shadow Ball', 'Thunder Wave', 'Electric', NULL, 'Timid', 'Pokeball', 'None', 50, 35, 10, 5, 'T029'),
('Razor', 212, 'Scizor', 'Bullet Punch', 'X-Scissor', 'Swords Dance', 'Knock Off', 'Bug', 'Steel', 'Adamant', 'Great Ball', 'None', 45, 30, 10, 5, 'T029'),
('Frostbite', 471, 'Glaceon', 'Ice Beam', 'Shadow Ball', 'Blizzard', 'Water Pulse', 'Ice', NULL, 'Modest', 'Pokeball', 'None', 40, 25, 10, 5, 'T029'),
('Steel', 208, 'Steelix', 'Iron Tail', 'Earthquake', 'Stealth Rock', 'Crunch', 'Steel', 'Ground', 'Impish', 'Ultra Ball', 'None', 50, 30, 10, 10, 'T029'),
('Pyro', 5, 'Charmeleon', 'Flamethrower', 'Dragon Rage', 'Fire Spin', 'Smokescreen', 'Fire', NULL, 'Brave', 'Great Ball', 'None', 40, 25, 10, 5, 'T030'),
('Stormy', 134, 'Vaporeon', 'Hydro Pump', 'Ice Beam', 'Shadow Ball', 'Aqua Ring', 'Water', NULL, 'Calm', 'Ultra Ball', 'None', 50, 35, 10, 5, 'T030'),
('Rocky', 112, 'Rhydon', 'Earthquake', 'Rock Blast', 'Megahorn', 'Crunch', 'Ground', 'Rock', 'Adamant', 'Great Ball', 'None', 45, 30, 15, 5, 'T030'),
('Flare', 38, 'Ninetales', 'Flamethrower', 'Solar Beam', 'Extrasensory', 'Will-O-Wisp', 'Fire', NULL, 'Modest', 'Pokeball', 'None', 45, 30, 10, 5, 'T030');











INSERT INTO pokemon (Nome, Pokedex, Nomedex, Ataque1, Ataque2, Ataque3, Ataque4, Tipo1, Tipo2, Nature, Pokebola, Item_pokemon, Combates, Vitorias, Derrotas, Empate, ID_Treinador)
VALUES
('Cinder', 136, 'Flareon', 'Flamethrower', 'Quick Attack', 'Superpower', 'Fire Fang', 'Fire', NULL, 'Adamant', 'Pokeball', 'None', 40, 25, 10, 5, 'T007'),
('Shadow', 94, 'Gengar', 'Shadow Ball', 'Sludge Bomb', 'Hypnosis', 'Dream Eater', 'Ghost', 'Poison', 'Timid', 'Dusk Ball', 'None', 55, 35, 15, 5, 'T002'),
('Fluffy', 36, 'Clefairy', 'Moonblast', 'Metronome', 'Sing', 'Body Slam', 'Fairy', NULL, 'Calm', 'Great Ball', 'None', 40, 25, 10, 5, 'T001'),
('Storm', 130, 'Gyarados', 'Waterfall', 'Dragon Dance', 'Ice Fang', 'Hyper Beam', 'Water', 'Flying', 'Brave', 'Pokeball', 'None', 65, 40, 20, 5, 'T002'),
('Thunder', 145, 'Zapdos', 'Thunderbolt', 'Drill Peck', 'Roost', 'Heat Wave', 'Electric', 'Flying', 'Modest', 'Ultra Ball', 'None', 70, 45, 20, 5, 'T004'),
('Echo', 196, 'Espeon', 'Psychic', 'Dazzling Gleam', 'Shadow Ball', 'Calm Mind', 'Psychic', NULL, 'Timid', 'Pokeball', 'None', 45, 30, 10, 5, 'T003'),
('Inferno', 59, 'Arcanine', 'Flamethrower', 'Crunch', 'Extreme Speed', 'Fire Fang', 'Fire', NULL, 'Brave', 'Pokeball', 'None', 50, 30, 15, 5, 'T010'),
('Aqua', 134, 'Vaporeon', 'Surf', 'Ice Beam', 'Shadow Ball', 'Hydro Pump', 'Water', NULL, 'Modest', 'Great Ball', 'None', 50, 30, 15, 5, 'T003'),
('Magma', 126, 'Magmar', 'Flamethrower', 'Psychic', 'Thunder Punch', 'Fire Blast', 'Fire', NULL, 'Hasty', 'Great Ball', 'None', 40, 25, 10, 5, 'T002'),
('Blossom', 182, 'Bellossom', 'Solar Beam', 'Moonblast', 'Stun Spore', 'Giga Drain', 'Grass', NULL, 'Calm', 'Pokeball', 'None', 40, 25, 10, 5, 'T004'),
('Vortex', 130, 'Gyarados', 'Waterfall', 'Dragon Dance', 'Hyper Beam', 'Ice Fang', 'Water', 'Flying', 'Brave', 'Ultra Ball', 'None', 60, 40, 15, 5, 'T009'),
('Rage', 115, 'Kangaskhan', 'Double-Edge', 'Crunch', 'Earthquake', 'Fake Out', 'Normal', NULL, 'Adamant', 'Great Ball', 'None', 45, 25, 15, 5, 'T009'),
('Blitz', 59, 'Arcanine', 'Flamethrower', 'Crunch', 'Extreme Speed', 'Fire Fang', 'Fire', NULL, 'Bold', 'Ultra Ball', 'None', 60, 40, 15, 5, 'T002'),
('Frostbite', 131, 'Lapras', 'Ice Beam', 'Surf', 'Dragon Dance', 'Perish Song', 'Ice', 'Water', 'Calm', 'Pokeball', 'None', 55, 35, 15, 5, 'T009'),
('Glare', 101, 'Electrode', 'Thunderbolt', 'Volt Switch', 'Explosion', 'Light Screen', 'Electric', NULL, 'Timid', 'Ultra Ball', 'None', 45, 30, 10, 5, 'T008'),
('Ivy', 3, 'Venusaur', 'Solar Beam', 'Sludge Bomb', 'Earthquake', 'Synthesis', 'Grass', 'Poison', 'Modest', 'Great Ball', 'None', 50, 30, 15, 5, 'T009'),
('Luna', 39, 'Jigglypuff', 'Dazzling Gleam', 'Hyper Voice', 'Sing', 'Body Slam', 'Fairy', 'Normal', 'Calm', 'Pokeball', 'None', 30, 15, 10, 5, 'T005'),
('Tempest', 149, 'Dragonite', 'Outrage', 'Dragon Dance', 'Hurricane', 'Thunder Punch', 'Dragon', 'Flying', 'Jolly', 'Ultra Ball', 'None', 65, 40, 20, 5, 'T006'),
('Pyro', 136, 'Flareon', 'Flamethrower', 'Quick Attack', 'Superpower', 'Fire Fang', 'Fire', NULL, 'Adamant', 'Pokeball', 'None', 50, 30, 15, 5, 'T006'),
('Flare', 126, 'Magmar', 'Flamethrower', 'Psychic', 'Thunder Punch', 'Fire Blast', 'Fire', NULL, 'Hasty', 'Great Ball', 'None', 40, 25, 10, 5, 'T008'),
('Crusher', 112, 'Rhydon', 'Rock Wrecker', 'Earthquake', 'Hammer Arm', 'Megahorn', 'Ground', 'Rock', 'Adamant', 'Ultra Ball', 'None', 50, 35, 10, 5, 'T005'),
('Boulder', 95, 'Onix', 'Rock Throw', 'Bind', 'Earthquake', 'Slam', 'Rock', 'Ground', 'Adamant', 'Ultra Ball', 'None', 50, 30, 15, 5, 'T007'),
('Spike', 111, 'Rhyhorn', 'Earthquake', 'Rock Blast', 'Megahorn', 'Crunch', 'Ground', 'Rock', 'Adamant', 'Pokeball', 'None', 35, 20, 10, 5, 'T008'),
('Whiskers', 52, 'Persian', 'Fake Out', 'Shadow Claw', 'Power Gem', 'U-turn', 'Normal', NULL, 'Jolly', 'Ultra Ball', 'None', 40, 25, 10, 5, 'T010'),
('Leafy', 3, 'Venusaur', 'Solar Beam', 'Sludge Bomb', 'Earthquake', 'Synthesis', 'Grass', 'Poison', 'Modest', 'Great Ball', 'None', 50, 30, 15, 5, 'T002'),
('Frost', 131, 'Lapras', 'Ice Beam', 'Surf', 'Dragon Dance', 'Perish Song', 'Ice', 'Water', 'Modest', 'Great Ball', 'None', 45, 30, 10, 5, 'T005'),
('Blaze', 5, 'Charmeleon', 'Flamethrower', 'Dragon Breath', 'Slash', 'Fire Fang', 'Fire', NULL, 'Brave', 'Pokeball', 'None', 40, 25, 10, 5, 'T005'),
('Tornado', 17, 'Pidgeotto', 'Gust', 'Quick Attack', 'Wing Attack', 'Feather Dance', 'Flying', 'Normal', 'Brave', 'Pokeball', 'None', 35, 20, 10, 5, 'T001'),
('Gemini', 18, 'Pidgeot', 'Hurricane', 'Brave Bird', 'Roost', 'Quick Attack', 'Flying', 'Normal', 'Brave', 'Pokeball', 'None', 35, 20, 10, 5, 'T004');


INSERT INTO pokemon (Nome, Pokedex, Nomedex, Ataque1, Ataque2, Ataque3, Ataque4, Tipo1, Tipo2, Nature, Pokebola, Item_pokemon, Combates, Vitorias, Derrotas, Empate, ID_Treinador)
VALUES
('Snappy', 159, 'Croconaw', 'Water Gun', 'Crunch', 'Ice Fang', 'Aqua Tail', 'Water', NULL, 'Adamant', 'Pokeball', 'None', 45, 30, 15, 5, 'T012'),
('Claw', 6, 'Charizard', 'Flamethrower', 'Dragon Claw', 'Roost', 'Fire Blast', 'Fire', 'Flying', 'Modest', 'Pokeball', 'None', 50, 30, 15, 5, 'T011'),
('Bramble', 45, 'Vileplume', 'Solar Beam', 'Sludge Bomb', 'Moonblast', 'Stun Spore', 'Grass', 'Poison', 'Calm', 'Ultra Ball', 'None', 45, 30, 10, 5, 'T011'),
('Hurricane', 149, 'Dragonite', 'Outrage', 'Thunder Punch', 'Fire Punch', 'Hurricane', 'Dragon', 'Flying', 'Adamant', 'Great Ball', 'None', 60, 40, 15, 5, 'T011'),
('Sunny', 38, 'Ninetales', 'Flamethrower', 'Solar Beam', 'Extrasensory', 'Will-O-Wisp', 'Fire', NULL, 'Modest', 'Great Ball', 'None', 45, 30, 10, 5, 'T014'),
('Fluffy', 39, 'Jigglypuff', 'Sing', 'Hyper Voice', 'Dazzling Gleam', 'Body Slam', 'Fairy', 'Normal', 'Timid', 'Great Ball', 'None', 35, 20, 10, 5, 'T012'),
('Ember', 4, 'Charmander', 'Flamethrower', 'Scratch', 'Dragon Claw', 'Fire Fang', 'Fire', NULL, 'Jolly', 'Pokeball', 'None', 35, 20, 10, 5, 'T013'),
('Wisp', 302, 'Sableye', 'Shadow Sneak', 'Fake Out', 'Will-O-Wisp', 'Knock Off', 'Ghost', 'Dark', 'Brave', 'Ultra Ball', 'None', 35, 20, 10, 5, 'T014'),
('Hydra', 130, 'Gyarados', 'Waterfall', 'Dragon Dance', 'Ice Fang', 'Crunch', 'Water', 'Flying', 'Brave', 'Ultra Ball', 'None', 50, 30, 15, 5, 'T013'),
('Flame', 5, 'Charmeleon', 'Flamethrower', 'Dragon Claw', 'Fire Fang', 'Slash', 'Fire', NULL, 'Hasty', 'Pokeball', 'None', 45, 30, 15, 5, 'T014'),
('Stormy', 55, 'Golduck', 'Surf', 'Ice Beam', 'Zen Headbutt', 'Aqua Tail', 'Water', NULL, 'Calm', 'Great Ball', 'None', 40, 25, 10, 5, 'T013'),
('Blade', 475, 'Gallade', 'Psycho Cut', 'Close Combat', 'Leaf Blade', 'Swords Dance', 'Psychic', 'Fighting', 'Adamant', 'Pokeball', 'None', 45, 30, 10, 5, 'T018'),
('Mystic', 131, 'Lapras', 'Ice Beam', 'Surf', 'Thunderbolt', 'Psychic', 'Water', 'Ice', 'Modest', 'Ultra Ball', 'None', 50, 30, 15, 5, 'T018'),
('Frost', 471, 'Glaceon', 'Ice Beam', 'Shadow Ball', 'Water Pulse', 'Blizzard', 'Ice', NULL, 'Timid', 'Great Ball', 'None', 40, 25, 10, 5, 'T018'),
('Talon', 6, 'Charizard', 'Flamethrower', 'Fly', 'Dragon Claw', 'Fire Blast', 'Fire', 'Flying', 'Adamant', 'Pokeball', 'None', 50, 30, 15, 5, 'T015'),
('Echo', 130, 'Gyarados', 'Waterfall', 'Crunch', 'Ice Fang', 'Dragon Dance', 'Water', 'Flying', 'Brave', 'Ultra Ball', 'None', 50, 30, 10, 10, 'T019'),
('Lava', 219, 'Magcargo', 'Lava Plume', 'Rock Slide', 'Shell Smash', 'Earth Power', 'Fire', 'Rock', 'Calm', 'Pokeball', 'None', 35, 20, 10, 5, 'T016'),
('Twister', 149, 'Dragonite', 'Outrage', 'Hurricane', 'Fire Punch', 'Extreme Speed', 'Dragon', 'Flying', 'Jolly', 'Pokeball', 'None', 55, 35, 15, 5, 'T017'),
('Spark', 135, 'Jolteon', 'Thunderbolt', 'Volt Switch', 'Thunder Wave', 'Shadow Ball', 'Electric', NULL, 'Timid', 'Pokeball', 'None', 45, 30, 15, 5, 'T018'),
('Thunder', 135, 'Jolteon', 'Thunderbolt', 'Shadow Ball', 'Volt Switch', 'Thunder Wave', 'Electric', NULL, 'Timid', 'Great Ball', 'None', 45, 30, 10, 5, 'T016'),
('Thunder', 135, 'Jolteon', 'Thunderbolt', 'Volt Switch', 'Shadow Ball', 'Thunder Wave', 'Electric', NULL, 'Timid', 'Pokeball', 'None', 45, 30, 15, 5, 'T020'),
('Razor', 452, 'Drapion', 'Poison Fang', 'Night Slash', 'Earthquake', 'Crunch', 'Poison', 'Dark', 'Adamant', 'Great Ball', 'None', 50, 30, 15, 5, 'T015'),
('Claw', 6, 'Charizard', 'Flamethrower', 'Dragon Claw', 'Fly', 'Roost', 'Fire', 'Flying', 'Brave', 'Ultra Ball', 'None', 50, 30, 15, 5, 'T017'),
('Wings', 227, 'Skarmory', 'Brave Bird', 'Roost', 'Spikes', 'Steel Wing', 'Steel', 'Flying', 'Impish', 'Ultra Ball', 'None', 50, 35, 10, 5, 'T020'),
('Fury', 110, 'Weezing', 'Sludge Bomb', 'Will-O-Wisp', 'Toxic', 'Explosion', 'Poison', NULL, 'Bold', 'Pokeball', 'None', 35, 20, 10, 5, 'T020'),
('Rocky', 112, 'Rhydon', 'Earthquake', 'Rock Blast', 'Megahorn', 'Crunch', 'Ground', 'Rock', 'Adamant', 'Great Ball', 'None', 40, 25, 10, 5, 'T020'),
('Spikey', 111, 'Rhyhorn', 'Earthquake', 'Stone Edge', 'Crunch', 'Megahorn', 'Ground', 'Rock', 'Adamant', 'Ultra Ball', 'None', 50, 35, 10, 5, 'T016'),
('Zapper', 160, 'Electabuzz', 'Thunderbolt', 'Volt Switch', 'Low Kick', 'Thunder Punch', 'Electric', NULL, 'Modest', 'Great Ball', 'None', 45, 30, 10, 5, 'T019'),
('Flare', 38, 'Ninetales', 'Flamethrower', 'Solar Beam', 'Will-O-Wisp', 'Extrasensory', 'Fire', NULL, 'Calm', 'Pokeball', 'None', 45, 30, 15, 5, 'T019'),
('Spark', 135, 'Jolteon', 'Thunderbolt', 'Volt Switch', 'Shadow Ball', 'Thunder Wave', 'Electric', NULL, 'Timid', 'Great Ball', 'None', 45, 30, 10, 5, 'T019'),
('Claw', 6, 'Charizard', 'Flamethrower', 'Dragon Claw', 'Fly', 'Roost', 'Fire', 'Flying', 'Brave', 'Ultra Ball', 'None', 50, 30, 15, 5, 'T017');